apiVersion: v1
kind: Service
metadata:
  name: covoiturage-registry-service
  namespace: argocd
  labels:
    app: covoiturage-registry-service
spec:
  type: NodePort
  selector:
    app: covoiturage-registry-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30506
