apiVersion: v1
kind: Service
metadata:
  name: covoiturage-config
  namespace: argocd
  labels:
    app: covoiturage-config
spec:
  type: NodePort
  selector:
    app: covoiturage-config
  ports:
    - port: 8811
      targetPort: 8811
      nodePort: 30504
