apiVersion: apps/v1
kind: Deployment
metadata:
  name: covoiturage-messenger-service
  namespace: argocd
  labels:
    app: covoiturage-messenger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covoiturage-messenger-service
  template:
    metadata:
      labels:
        app: covoiturage-messenger-service
    spec:
      containers:
        - name: covoiturage-messenger-service
          image: jiihed/covoiturage-messenger-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "admin"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "1"
            - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
              value: "2"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server"
            - name: EUREKA_CLIENT_HEALTHCHECK_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_LEASE_DURATION
              value: "5"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_SECURITY_USER_NAME
              value: admin
            - name: SPRING_SECURITY_USER_PASSWORD
              value: adminUserForAccessingActuatorEndpoints0000
            - name: SPRING_SECURITY_USER_ROLES
              value: ADMIN
            - name: EUREKA_INSTANCE_METADATA_MAP_USER_NAME
              value: admin
            - name: EUREKA_INSTANCE_METADATA_MAP_USER_PASSWORD
              value: adminUserForAccessingActuatorEndpoints0000
            - name: SPRING_BOOT_ADMIN_INSTANCE_AUTH_ENABLED
              value: "true"