apiVersion: apps/v1
kind: Deployment
metadata:
  name: covoiturage-messenger-service
  namespace: argocd
  labels:
    app: covoiturage-messenger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covoiturage-messenger-service
  template:
    metadata:
      labels:
        app: covoiturage-messenger-service
    spec:
      containers:
        - name: covoiturage-messenger-service
          image: covoiturage-messenger-service:1.1
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "admin"