apiVersion: v1
kind: Service
metadata:
  name: covoiturage-authentification-service
  namespace: argocd
  labels:
    app: covoiturage-authentification-service
spec:
  type: NodePort
  selector:
    app: covoiturage-authentification-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30502
