apiVersion: apps/v1
kind: Deployment
metadata:
  name: covoiturage-common
  namespace: argocd
  labels:
    app: covoiturage-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covoiturage-common
  template:
    metadata:
      labels:
        app: covoiturage-common
    spec:
      containers:
        - name: covoiturage-common
          image: jiihed/covoiturage-common:1.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "admin"
            - name: SPRING_DATA_MONGODB_AUTOINDEXCREATION
              value: "false"
