apiVersion: v1
kind: Service
metadata:
  name: covoiturage-common
  namespace: argocd
  labels:
    app: covoiturage-common
spec:
  type: NodePort
  selector:
    app: covoiturage-common
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30503
