apiVersion: apps/v1
kind: Deployment
metadata:
  name: covoiturage-ui
  namespace: argocd
  labels:
    app: covoiturage-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covoiturage-ui
  template:
    metadata:
      labels:
        app: covoiturage-ui
    spec:
      containers:
        - name: covoiturage-ui
          image: jiihed/covoiturage-ui:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
