apiVersion: apps/v1
kind: Deployment
metadata:
  name: covoiturage-ui
  namespace: argocd
  labels:
    app: covoiturage-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covoiturage-ui
  template:
    metadata:
      labels:
        app: covoiturage-ui
    spec:
      containers:
        - name: covoiturage-ui
          image: localhost:5000/covoiturage-ui:2.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
