apiVersion: v1
kind: Service
metadata:
  name: covoiturage-ui
  namespace: argocd
  labels:
    app: covoiturage-ui
spec:
  type: NodePort
  selector:
    app: covoiturage-ui
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30509
