apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard
  namespace: argocd
  labels:
    app: admin-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-dashboard
  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
      containers:
        - name: covoiturage-admin-console-server
          image: covoiturage-admin-console-server:1.1
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 7777
