apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard
  namespace: argocd
  labels:
    app: admin-dashboard
spec:
  type: NodePort
  selector:
    app: admin-dashboard
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30500
