apiVersion: v1
kind: Service
metadata:
  name: covoiturage-swagger
  namespace: argocd
  labels:
    app: covoiturage-swagger
spec:
  type: NodePort
  selector:
    app: covoiturage-swagger
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30508
