apiVersion: apps/v1
kind: Deployment
metadata:
  name: co-api-gateway
  namespace: argocd
  labels:
    app: co-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: co-api-gateway
  template:
    metadata:
      labels:
        app: co-api-gateway
    spec:
      containers:
        - name: co-api-gateway
          image: jiihed/covoiturage-api-gateway:1.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8443
