apiVersion: v1
kind: Service
metadata:
  name: co-api-gateway
  namespace: argocd
  labels:
    app: co-api-gateway
spec:
  type: NodePort
  selector:
    app: co-api-gateway
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30501
